#MQTT CLIENT CONFIGURATIONS
clientSub:
  clientId: "cg_subscriber"
  serverAddress: "tcp://test.mosquitto.org:1884"
  qos: 1
  connectionTimeout: 1
  writeTimeout: 1
  keepAlive: 30
  pingTimeout: 1
  connectRetry: true
  autoConnect: true
  orderMaters: false
  userName: "rw"
  password: "readwrite"
  tlsConn: false
  rootCAPath: "./certs/sub/xxxxxxxx"
  clientKeyPath: "./certs/sub/xxxxxxxx"
  privateKeyPath: "./certs/sub/xxxxxxxx"
  insecureSkipVerify: true

clientPub:
  clientId: "cgedgedebug"
  serverAddress: "tcp://172.24.50.102:1883"
  qos: 1
  connectionTimeout: 1
  writeTimeout: 1
  keepAlive: 30
  pingTimeout: 1
  connectRetry: true
  autoConnect: true
  orderMaters: false
  userName: ""
  password: ""
  tlsConn: false
  rootCAPath: "./certs/pub/empty_ca.pem"
  clientKeyPath: "./certs/pub/empty_cert.pem"
  privateKeyPath: "./certs/pub/empty_key.pem"
  insecureSkipVerify: true
  translateTopic: false
  publishInterval: 250

#LOGS
logs:
  subPayload: true
  debug: true
  warning: true
  error: true
  critical: true

#TOPICS TO SUBSCRIBE TO
topicsSub:
  topic:
    - "cgedge-mosquitto/#"

#TOPICS TO PUBLISH TO
topicsPub:
  topic:
    - "mqttpubsub/test"