#MQTT CLIENT CONFIGURATIONS
clientSub:
  clientId: "cg_subscriber"
  serverAddress: "tcp://test.mosquitto.org:1884"
  qos: 1
  connectionTimeout: 1
  writeTimeout: 1
  keepAlive: 30
  pingTimeout: 1
  connectRetry: true
  autoConnect: true
  orderMaters: false
  userName: "rw"
  password: "readwrite"
  tlsConn: false
  rootCA: "-----BEGIN CERTIFICATE-----\nROOTCA\n-----END CERTIFICATE-----"
  clientKey: "-----BEGIN CERTIFICATE-----\nCERTIFICATE\n-----END CERTIFICATE-----"
  privateKey: "-----BEGIN RSA PRIVATE KEY-----\nPRIVATEKEY\n-----END RSA PRIVATE KEY-----"
  insecureSkipVerify: true

clientPub:
  clientId: "cgedgedebug"
  serverAddress: "tcp://172.24.50.102:1883"
  qos: 1
  connectionTimeout: 1
  writeTimeout: 1
  keepAlive: 30
  pingTimeout: 1
  connectRetry: true
  autoConnect: true
  orderMaters: false
  userName: ""
  password: ""
  tlsConn: false
  rootCA: "-----BEGIN CERTIFICATE-----\nROOTCA\n-----END CERTIFICATE-----"
  clientKey: "-----BEGIN CERTIFICATE-----\nCERTIFICATE\n-----END CERTIFICATE-----"
  privateKey: "-----BEGIN RSA PRIVATE KEY-----\nPRIVATEKEY\n-----END RSA PRIVATE KEY-----"
  insecureSkipVerify: true
  translateTopic: false
  publishInterval: 50

#LOGS
logs:
  subPayload: false
  debug: false
  warning: false
  error: true
  critical: true

#TOPICS TO SUBSCRIBE TO
topicsSub:
  topic:
    - "cg-connector/#"

#TOPICS TO PUBLISH TO
topicsPub:
  topic:
    - "mqttpubsub/test"